/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp7.Vistas;

import java.util.HashSet;
import tp7.Alumno;
import tp7.Materia;

/**
 *
 * @author rataq
 */
public class Inscripciones extends javax.swing.JFrame {
    
    private static HashSet <Alumno> estudiantes = new HashSet<>();
    private static HashSet <Materia> materias = new HashSet<>();

    /**
     * Creates new form FormularioDeMaterias
     */
    public Inscripciones() {
        initComponents();
    }

    public static HashSet<Alumno> getEstudiantes() {
        return estudiantes;
    }

    public static HashSet<Materia> getMaterias() {
        return materias;
    }
    
    public void agregarMateria(Materia m){
        materias.add(m);
    }
    public void agregarAlumno(Alumno a){
        estudiantes.add(a);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jMenu1 = new javax.swing.JMenu();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmFormularios = new javax.swing.JMenu();
        jmiFormularioAlumnos = new javax.swing.JMenuItem();
        jmiFormularioMaterias = new javax.swing.JMenuItem();
        jmiFormularioInscripcion = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane2.setBackground(new java.awt.Color(102, 153, 255));

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );

        jmFormularios.setText("Formularios");
        jmFormularios.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jmFormulariosMenuSelected(evt);
            }
        });

        jmiFormularioAlumnos.setText("Formulario de Alumnos");
        jmiFormularioAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormularioAlumnosActionPerformed(evt);
            }
        });
        jmFormularios.add(jmiFormularioAlumnos);

        jmiFormularioMaterias.setText("Formulario de Materias");
        jmiFormularioMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormularioMateriasActionPerformed(evt);
            }
        });
        jmFormularios.add(jmiFormularioMaterias);

        jmiFormularioInscripcion.setText("Formulario de Inscripción");
        jmiFormularioInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormularioInscripcionActionPerformed(evt);
            }
        });
        jmFormularios.add(jmiFormularioInscripcion);

        jMenuBar1.add(jmFormularios);

        jMenu2.setText("Salir");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmFormulariosMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jmFormulariosMenuSelected
        // TODO add your handling code here:
    }//GEN-LAST:event_jmFormulariosMenuSelected

    private void jmiFormularioAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormularioAlumnosActionPerformed
        // TODO add your handling code here:
        jmFormularios.removeAll();
        jmFormularios.repaint();
        FormularioDeAlumnos cole = new FormularioDeAlumnos();   
        cole.setVisible(true);
        jmFormularios.add(cole);
    }//GEN-LAST:event_jmiFormularioAlumnosActionPerformed

    private void jmiFormularioMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormularioMateriasActionPerformed
        // TODO add your handling code here:
        jmFormularios.removeAll();
        jmFormularios.repaint();
        FormularioDeMaterias cole = new FormularioDeMaterias();   
        cole.setVisible(true);
        jmFormularios.add(cole);
    }//GEN-LAST:event_jmiFormularioMateriasActionPerformed

    private void jmiFormularioInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormularioInscripcionActionPerformed
        // TODO add your handling code here:
        jmFormularios.removeAll();
        jmFormularios.repaint();
        FormularioDeInscripcion cole = new FormularioDeInscripcion();   
        cole.setVisible(true);
        jmFormularios.add(cole);
    }//GEN-LAST:event_jmiFormularioInscripcionActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenu2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inscripciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inscripciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inscripciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inscripciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inscripciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmFormularios;
    private javax.swing.JMenuItem jmiFormularioAlumnos;
    private javax.swing.JMenuItem jmiFormularioInscripcion;
    private javax.swing.JMenuItem jmiFormularioMaterias;
    // End of variables declaration//GEN-END:variables
}
